name: uniid
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.31.0
      - aiofiles==23.2.1
      - albucore==0.0.16
      - albumentations==1.4.15
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==2.4.1
      - av==12.3.0
      - beautifulsoup4==4.12.3
      - braceexpand==0.1.7
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cramjam==2.9.1
      - cycler==0.12.1
      - cython==3.0.11
      - debugpy==1.8.5
      - decorator==5.1.1
      - diffusers==0.31.0.dev0
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - eval-type-backport==0.2.0
      - executing==2.1.0
      - fastapi==0.115.8
      - fastparquet==2024.11.0
      - ffmpy==0.5.0
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - ftfy==6.2.3
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==5.14.0
      - gradio-client==1.7.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - humanfriendly==10.0
      - idna==3.7
      - imageio==2.35.1
      - importlib-metadata==8.2.0
      - insightface==0.7.3
      - ipykernel==6.29.5
      - ipython==8.27.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.2
      - onnxruntime-gpu==1.19.2
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.15
      - packaging==24.1
      - pandas==2.2.3
      - parso==0.8.4
      - peft==0.12.0
      - pexpect==4.9.0
      - photomaker==0.2.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - prettytable==3.11.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.1
      - pyzmq==26.2.0
      - regex==2024.7.24
      - requests==2.32.3
      - rich==13.9.4
      - ruff==0.9.4
      - safehttpx==0.1.6
      - safetensors==0.4.3
      - scienceplots==2.1.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.45.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.2
      - torchvision==0.19.0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.47.0
      - triton==3.0.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.2
      - uvicorn==0.34.0
      - wandb==0.17.5
      - wcwidth==0.2.13
      - webdataset==0.2.110
      - websockets==14.2
      - xformers==0.0.27.post2
      - zipp==3.19.2
